# Generated by Django 4.1.3 on 2023-07-18 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bangazonapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='isAvailble',
            new_name='isAvailable',
        ),
    ]
